# Generated by Django 3.1.7 on 2021-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
