# Generated by Django 3.1.7 on 2021-05-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210507_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='username',
            new_name='name',
        ),
    ]
