# Generated by Django 3.1.7 on 2021-05-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210507_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='Category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='write location and price', max_length=300),
        ),
    ]
