# Generated by Django 3.1.7 on 2021-05-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210509_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='img',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.category'),
        ),
    ]
