# Generated by Django 3.1.7 on 2021-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
