# Generated by Django 3.1.7 on 2021-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20210517_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
