# Generated by Django 3.1.7 on 2021-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
