# Generated by Django 3.1.7 on 2021-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20210519_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='enquire',
            old_name='img',
            new_name='product',
        ),
    ]
