# Generated by Django 3.1.7 on 2021-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20210719_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
